# Generated by Django 4.1.6 on 2023-02-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='file',
            field=models.FileField(upload_to='ml_models/'),
        ),
    ]
